In [1]:
import pandas as pd
import numpy as np
from numpy import dot

from numpy.linalg import norm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df=pd.read_excel("jeju place5.xlsx",na_filter=True)
del df['Unnamed: 0']

In [12]:
df

콘텐츠ID 콘텐츠분류                   제목  \
0     CNTS_000000000020419   음식점               초밥군커피씨   
1     CNTS_000000000022944   음식점                 73st   
2     CNTS_000000000020436   음식점                호돌이식당   
3     CNTS_000000000021195   음식점             비양도 올레카페   
4     CNTS_000000000020732   음식점              협재삼춘네횟집   
...                    ...   ...                  ...   
3624  CNTS_000000000022182   음식점  몽키비치클럽 Monkey Beach   
3625  CNTS_000000000022252    숙박               힐링캠프펜션   
3626  CNTS_000000000022237   음식점                 유나카페   
3627  CNTS_200000000008003   관광지               동백포레스트   
3628  CNTS_200000000012075   관광지           헌마공신김만일기념관   

                            지번주소                     도로명주소    지역분류         위도  \
0             제주특별자치도 제주시 흥운길 46        제주특별자치도 제주시 흥운길 46     제주시  33.512722   
1         제주특별자치도 제주시 해안동 1977-1      제주특별자치도 제주시 해안마을길 73     제주시  33.456950   
2       제주특별자치도 제주시 한림읍 협재리 3026  제주특별자치도 제주시 한림읍 비양도길 284   제주시서부  33.406414   
3       제주특별자치도 제주시 한림읍 협재리 2992   제주특별자치도 제주시 한림읍 비양도길 24   제주시서부  33.405266   
4     제주특별자치도 제주시 한림읍 협재리 2514-9   제주특별자치도 제주시 한림읍 한림로 318   제주시서부  33.392150   
...                          ...                       ...     ...        ...   
3624             서귀포시 색달동 2822-2       서귀포시 중문관광로72번길 29-9    서귀포시  33.249680   
3625         서귀포시 남원읍 위미리 3392-1         서귀포시 남원읍 위미항구로 96  서귀포시동부  33.282875   
3626           서귀포시 남원읍 신례리 57-1          서귀포시 남원읍 공천포로 81  서귀포시동부  33.266018   
3627           서귀포시 남원읍 신례리 1767         서귀포시 남원읍 신례리 1767  서귀포시동부  33.299995   
3628            서귀포시 남원읍 서성로 919          서귀포시 남원읍 서성로 919  서귀포시동부        NaN   

              경도   평점   조회수  ...  리뷰수  SNS공유수     인기점수  \
0     126.512820  4.0  3478  ...    3       2   6980.0   
1     126.455150  4.0  2374  ...    1       2   4756.0   
2     126.230350  4.0  2180  ...    2       0   4370.0   
3     126.228966  5.0  1448  ...    1       4   2901.0   
4     126.239560  3.0   768  ...    1       0   1541.0   
...          ...  ...   ...  ...  ...     ...      ...   
3624  126.411360  NaN  3509  ...    0       2   7024.0   
3625  126.655720  NaN   762  ...    0       2   1524.0   
3626  126.641820  NaN   908  ...    0       1   1816.0   
3627  126.629794  0.0  7682  ...    0       6  15379.0   
3628         NaN  0.0   142  ...    0       0    287.0   

                                                     태그  \
0                  #초밥 #용초밥 #왕초밥 #일식 #음식 #스시 #2022고메페스타   
1     #카페 #디저트 #브런치 #피자 #샐러드 #음식 #페페로니햄피자 #고르곤졸라화덕피자...   
2                    #보말죽 #한치물회 #회덮밥 #매운탕 #전복물회 #음식 #한치   
3     #카페 #커피 #생과일주스 #빙수 #음식 #아메리카노 #수제청 #수제청음료 #에이드...   
4     #횟집 #회 #회코스 #음식 #갈치조림 #제주갈치조림 #고등어조림 #갈치국 #물회 ...   
...                                                 ...   
3624                                               #음식    
3625  #숙소 #휴양펜션 #펜션 #캠핑 #독채 #온돌방 #바비큐 #단체여행객 #공공와이파이...   
3626  #카페 #커피 #생과일주스 #감귝샐러드 #음식 #보말칼국수 #허니브레드 #자몽에이드...   
3627             #커플 #친구 #맑음 #경관/포토 #겨울 #자연경관 #동백 #포토스팟   
3628  #커플 #부모 #혼자 #친구 #아이 #맑음 #흐림 #비.눈 #경관/포토 #휴식/힐링...   

                                                     사진  \
0     https://api.cdn.visitjeju.net/photomng/imgpath...   
1     https://api.cdn.visitjeju.net/photomng/imgpath...   
2     https://api.cdn.visitjeju.net/photomng/imgpath...   
3     https://api.cdn.visitjeju.net/photomng/imgpath...   
4     https://api.cdn.visitjeju.net/photomng/imgpath...   
...                                                 ...   
3624  https://api.cdn.visitjeju.net/photomng/imgpath...   
3625  https://api.cdn.visitjeju.net/photomng/imgpath...   
3626  https://api.cdn.visitjeju.net/photomng/imgpath...   
3627  https://api.cdn.visitjeju.net/photomng/imgpath...   
3628  https://api.cdn.visitjeju.net/photomng/imgpath...   

                                                     소개  \
0                                크기가 어마어마한 직접 만들어먹는 용초밥   
1                           엔티크하고 분위기있는 인테리어를 갖춘 브런치 카페   
2                                      인기메뉴는 호돌이덮밥과 보말죽   
3           

In [4]:
dfe=df.groupby(df['콘텐츠분류']).get_group('음식점')
dfs=df.groupby(df['콘텐츠분류']).get_group('숙박')
dfg=df.groupby(df['콘텐츠분류']).get_group('관광지')

In [5]:
dfe=dfe.dropna(subset=['리뷰'])
dfs=dfs.dropna(subset=['리뷰'])
dfg=dfg.dropna(subset=['리뷰'])

In [6]:
from konlpy.tag import Kkma
from collections import Counter
kkma=Kkma()

In [9]:
list=[]
for i in range(0,len(dfs)):
    list+=kkma.nouns(dfs.iloc[i,-4])
count=Counter(list)
count.most_common(50)

[('제주', 166),
 ('여행', 84),
 ('곳', 66),
 ('수', 64),
 ('도', 56),
 ('제주도', 50),
 ('호텔', 48),
 ('하우스', 44),
 ('숙소', 42),
 ('바다', 41),
 ('조식', 41),
 ('분', 40),
 ('친절', 39),
 ('게스트', 38),
 ('아침', 36),
 ('가족', 35),
 ('시설', 33),
 ('게스트하우스', 31),
 ('숙박', 30),
 ('션', 29),
 ('추천', 29),
 ('때', 28),
 ('방', 27),
 ('다음', 26),
 ('사장님', 25),
 ('펜', 25),
 ('펜션', 25),
 ('방문', 24),
 ('분위기', 24),
 ('위치', 24),
 ('제주여행', 24),
 ('1', 23),
 ('2', 23),
 ('월', 23),
 ('박', 23),
 ('시', 22),
 ('가격', 22),
 ('공항', 21),
 ('아이', 21),
 ('편안', 21),
 ('리조트', 20),
 ('거', 20),
 ('시간', 20),
 ('집', 20),
 ('친구', 20),
 ('객실', 19),
 ('최고', 19),
 ('일', 19),
 ('만족', 19),
 ('앞', 19)]

In [11]:
list=[]
for i in range(0,len(dfg)):
    list+=kkma.nouns(dfg.iloc[i,-4])
count=Counter(list)
count.most_common(50)

[('제주', 669),
 ('곳', 288),
 ('도', 281),
 ('여행', 280),
 ('수', 278),
 ('제주도', 249),
 ('길', 191),
 ('가을', 175),
 ('제주여행', 173),
 ('분', 166),
 ('바다', 160),
 ('가족', 152),
 ('사진', 151),
 ('코스', 147),
 ('시간', 146),
 ('중', 143),
 ('월', 142),
 ('우리', 141),
 ('때', 138),
 ('일', 137),
 ('날', 137),
 ('년', 135),
 ('아이', 134),
 ('여름', 131),
 ('추억', 129),
 ('사람', 123),
 ('생각', 122),
 ('제주가을', 116),
 ('나', 115),
 ('추천', 114),
 ('풍경', 114),
 ('저', 113),
 ('하늘', 107),
 ('처음', 103),
 ('체험', 103),
 ('겨울', 101),
 ('바람', 101),
 ('아름', 97),
 ('시', 97),
 ('친구', 97),
 ('힐링', 97),
 ('날씨', 95),
 ('행복', 94),
 ('자연', 94),
 ('모습', 94),
 ('방문', 92),
 ('마음', 92),
 ('올레', 92),
 ('3', 90),
 ('장소', 90)]

In [8]:
list=[]
for i in range(0,len(dfe)):
    list+=kkma.nouns(dfe.iloc[i,-1])
count=Counter(list)
count.most_common(50)


[('제주', 450),
 ('맛', 303),
 ('집', 214),
 ('도', 185),
 ('곳', 181),
 ('제주도', 168),
 ('여행', 153),
 ('수', 145),
 ('맛집', 102),
 ('추천', 98),
 ('카페', 97),
 ('식당', 87),
 ('음식', 79),
 ('최고', 77),
 ('먹거리', 76),
 ('분', 74),
 ('바다', 71),
 ('저', 69),
 ('방문', 69),
 ('근처', 68),
 ('돼지', 66),
 ('때', 66),
 ('시', 65),
 ('가격', 64),
 ('분위기', 64),
 ('커피', 62),
 ('중', 60),
 ('월', 59),
 ('회', 58),
 ('친절', 58),
 ('유명', 58),
 ('제주여행', 58),
 ('흑', 57),
 ('메뉴', 54),
 ('고기', 54),
 ('나', 54),
 ('사람', 52),
 ('처음', 51),
 ('사장님', 48),
 ('시간', 48),
 ('밥', 46),
 ('생각', 45),
 ('여기', 45),
 ('전', 45),
 ('거', 45),
 ('국물', 43),
 ('안', 43),
 ('강추', 42),
 ('국수', 42),
 ('인생', 41)]

In [11]:
count.most_common(10)

[('제주', 450),
 ('맛', 303),
 ('집', 214),
 ('도', 185),
 ('곳', 181),
 ('제주도', 168),
 ('여행', 153),
 ('수', 145),
 ('맛집', 102),
 ('추천', 98)]

In [10]:
# 코드 수정
# 유사도 점수에 따라 추천
# 해시태그 빈도 
tfidf_vectorizer = TfidfVectorizer()

sentence=['맛집 추천 최고 친절 강추']

cos_sim=[]

for i in range(0,len(dfe)):
    sentence.append(dfe.iloc[i,-4])
    
tfidf_matrix = tfidf_vectorizer.fit_transform(sentence) 

for i in range(0,len(dfe)):
    a=i+1;b=i+2
    cos_similar=cosine_similarity(tfidf_matrix[0:1],tfidf_matrix[a:b])
    print("기준 문장과 ",i,"번째 문장과의 코사인 유사도: ",cos_similar)
    cos_sim.append(cos_similar)

기준 문장과  0 번째 문장과의 코사인 유사도:  [[0.01825762]]
기준 문장과  1 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  2 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  3 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  4 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  5 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  6 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  7 번째 문장과의 코사인 유사도:  [[0.03414735]]
기준 문장과  8 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  9 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  10 번째 문장과의 코사인 유사도:  [[0.01128904]]
기준 문장과  11 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  12 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  13 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  14 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  15 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  16 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  17 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  18 번째 문장과의 코사인 유사도:  [[0.04217418]]
기준 문장과  19 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  20 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  21 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  22 번째 문장과의 코사인 유사도:  [[0.03600279]]
기준 문장과  23 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  24 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  25 번째 문장과의 코사인 유사도:  [[0.01699331]]
기준 문장과  26 번째 문장과의 코사인 유사도

기준 문장과  265 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  266 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  267 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  268 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  269 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  270 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  271 번째 문장과의 코사인 유사도:  [[0.07331728]]
기준 문장과  272 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  273 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  274 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  275 번째 문장과의 코사인 유사도:  [[0.03395408]]
기준 문장과  276 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  277 번째 문장과의 코사인 유사도:  [[0.04614864]]
기준 문장과  278 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  279 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  280 번째 문장과의 코사인 유사도:  [[0.00744486]]
기준 문장과  281 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  282 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  283 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  284 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  285 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  286 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  287 번째 문장과의 코사인 유사도:  [[0.06231095]]
기준 문장과  288 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  289 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  290 번째 문장과의 코사인 유사도:  [[0.]

기준 문장과  492 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  493 번째 문장과의 코사인 유사도:  [[0.03640816]]
기준 문장과  494 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  495 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  496 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  497 번째 문장과의 코사인 유사도:  [[0.01336905]]
기준 문장과  498 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  499 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  500 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  501 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  502 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  503 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  504 번째 문장과의 코사인 유사도:  [[0.07582103]]
기준 문장과  505 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  506 번째 문장과의 코사인 유사도:  [[0.00968423]]
기준 문장과  507 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  508 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  509 번째 문장과의 코사인 유사도:  [[0.05224163]]
기준 문장과  510 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  511 번째 문장과의 코사인 유사도:  [[0.0533729]]
기준 문장과  512 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  513 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  514 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  515 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  516 번째 문장과의 코사인 유사도:  [[0.]]
기준 문장과  517 번째 문장과의 코사인 유사도:

In [13]:
c=np.array(cos_sim,dtype=float)
c=c.tolist()
arr=[]
for i in range(0,len(c)):
    arr.append(c[i][0][0])
dfe['코사인']=arr

In [10]:
cos_sim

[array([[0.01825762]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03414735]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.01128904]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.04217418]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03600279]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.01699331]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.11845215]]),
 array([[0.01113352]]),
 array([[0.04428971]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.0532374]]),
 array([[0.]]),
 array([[0.0407662]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.01617391]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02833177]]),
 array([[0.]]),
 array([[0.]]),
 a

In [84]:
dfe.sort_values('코사인',ascending=False)

콘텐츠ID 콘텐츠분류                     제목  \
2443  CNTS_200000000007602   음식점         스카이 온 파이브 다이닝    
3373  CNTS_200000000007943   음식점                  카페이피엘   
2240  CNTS_000000000001185   음식점                  강해일횟집   
175   CNTS_200000000010454   음식점                영림흑돼지가든   
2275  CNTS_000000000000785   음식점                  이어도식당   
...                    ...   ...                    ...   
1206  CNTS_000000000020245   음식점  살롱드라방 SALON de LAVANT   
1199  CNTS_000000000018359   음식점                  비바리짬뽕   
1198  CNTS_000000000020659   음식점                    불만나   
1197  CNTS_000000000020623   음식점               바다속고등어쌈밥   
3627  CNTS_000000000022021   음식점                  모슬포에서   

                                                   지번주소  \
2443  제주특별자치도 서귀포시 안덕면 신화역사로304번길 38 메리어트관 제주신화월드 호텔...   
3373                  제주특별자치도 서귀포시 남원읍 위미리 3166-1 카페이피엘   
2240                         제주특별자치도 서귀포시 표선면 표선리 40-31   
175                            제주특별자치도 제주시 한림읍 대림리 1803   
2275             제주특별자치도 서귀포시 표선면 성읍정의현로22번길 10-1 (성읍리)   
...                                                 ...   
1206                           제주특별자치도 제주시 애월읍 하가리 1415   
1199                         제주특별자치도 제주시 애월읍 하귀1리 138-1   
1198                         제주특별자치도 제주시 애월읍 하귀1리 142-2   
1197                          제주특별자치도 제주시 애월읍 하귀1리 1548   
3627                                      대정읍 하모리 824-3   

                                                  도로명주소    지역분류         위도  \
2443  제주특별자치도 서귀포시 안덕면 신화역사로304번길 38 메리어트관 제주신화월드 호텔...  서귀포시서부  33.301750   
3373               제주특별자치도 서귀포시 남원읍 위미항구로 8 (위미리) 카페이피엘  서귀포시동부  33.275109   
2240                          제주특별자치도 서귀포시 표선면 표선당포로 14  서귀포시동부  33.325714   
175                             제주특별자치도 제주시 한림읍 한수풀로 30   제주시서부  33.417789   
2275                   제주특별자치도 서귀포시 표선면 성읍정의현로22번길 10-1  서귀포시동부  33.384068   
...                                                 ...     ...        ...   
1206                          제주특별자치도 제주시 애월읍 하가로 146-9   제주시서부  33.499622   
1199                            제주특별자치도 제주시 애월읍 하귀9길 11   제주시서부  33.485847   
1198                            제주특별자치도 제주시 애월읍 하귀5길 14   제주시서부  33.481340   
1197                          제주특별자치도 제주시 애월읍 일주서로 7089   제주시서부  33.484203   
3627                              서귀포시 대정읍 영서중로13번길 9-9  서귀포시서부  33.221510   

              경도   평점    조회수  좋아요수  리뷰수  SNS공유수     인기점수  \
2443  126.320646  5.0  10038    28   35       6  20335.0   
3373  126.656957  5.0   1842     1    1       1   3692.0   
2240  126.844440  5.0   1990     0    1       0   3985.0   
175   126.266104  5.0   1328     8    4       6   2700.0   
2275  126.802080  5.0  10353     5    2       7  20731.0   
...          ...  ...    ...   ...  ...     ...      ...   
1206  126.531190  4.0   6708     7   13       4  13502.0   
1199  126.415530  4.0   2769     0    3       0   5553.0   
1198  126.415110  3.0    488     0    1       0    981.0   
1197  126.406830  4.0   7679     0    8       2  15398.0   
3627  126.254760  5.0   1569     0    1       0   3143.0   

                                                     태그  \
2443         #스카이온파이브그릴 #스테이크 #와인 #레스토랑 #음식 #뷔페 #제주신화월드   
3373    #베이커리카페 #보타닉카페 #커피 #브런치 #위미리카노 #음식 #도시락 #디저트 #빵   
2240  #회 #횟집 #해산물 #매운탕 #음식 #갈치구이 #갈치조림 #고등어구이 #해물뚝배기...   
175           #흑돼지 #한림 #오겹살 #갈비 #냉면 #음식 #흑돼지구이 #삼겹살 #식당   
2275                 #돼지불고기정식 #갈치조림 #옥돔정식 #성게국수 #한식 #음식   
...                                                 ...   
1206        #카페 #팬케이크 #브런치 #음식 #아메리카노 #에스프레소 #카페라떼 #케이크   
1199  #짬뽕 #찹쌀탕수육 #중식 #음식 #크림짬뽕 #해물짬뽕 #해물볶음짬뽕 #해물짜장 #...   
1198                           #흑오겹살 #매콤불고기 #김치말이국수 #음식   
1197  #갈치조림 #옥돔구이 #해물뚝배기 #한치물회 #쌈밥 #음식 #고등어 #전복뚝배기 #...   
3627              #녹두빈대떡 #보말톳메밀전 #흑돼지김치전 #깅이죽 #성게김밥 #음식   

                                                     사진  \
2443  https://api.cdn.visitjeju.net/photomng/imgpath...   
3373  https://api.cdn.visitjeju.net/photomng/imgpath...   
2240  https://api.cdn.visitjeju.net/photomng/imgpath...   


In [85]:
dfg=df.groupby(df['콘텐츠분류']).get_group('관광지')
dfg=dfg.dropna(subset=['리뷰'])
dfg

콘텐츠ID 콘텐츠분류                 제목                      지번주소  \
7     CNTS_000000000018385   관광지          김경숙해바라기농장       제주특별자치도 제주시 회천동 391   
19    CNTS_000000000022852   관광지       곤흘동(곤을동) 마을터     제주특별자치도 제주시 화북1동 4438   
25    CONT_000000000500295   관광지                삼각봉  제주특별자치도 제주시 해안동 산 220-13   
26    CNTS_000000000019989   관광지              어리목계곡  제주특별자치도 제주시 해안동 산 220-13   
29    CNTS_000000000020611   관광지            아날로그감귤밭      제주특별자치도 제주시 해안동 2463   
...                    ...   ...                ...                       ...   
3601  CNTS_000000000022135   관광지          포레스트 판타지아        서귀포시 안덕면 일주서로 1836   
3602  CNTS_000000000022771   관광지             신화테마파크    서귀포시 안덕면 신화역사로304번길 98   
3610  CNTS_000000000022377   관광지               성산포항        서귀포시 성산읍 성산리 347-9   
3626  CNTS_000000000022006   관광지  참살이마을 명도암 농어촌체험마을                 봉개동 270-3   
3628  CNTS_000000000022752   관광지         이승이오름(이승악)           [object Object]   

                             도로명주소    지역분류         위도          경도   평점    조회수  \
7            제주특별자치도 제주시 번영로 854-1     NaN  33.477360  126.627670  5.0  64213   
19           제주특별자치도 제주시 화북1동 4438     제주시  33.521984  126.557390  5.0   2260   
25       제주특별자치도 제주시 1100로 2070-61     NaN  33.361667  126.529167  5.0   3581   
26       제주특별자치도 제주시 1100로 2070-61     NaN  33.396788  126.487853  5.0   8612   
29           제주특별자치도 제주시 해안마을8길 46     NaN  33.455590  126.451096  4.0  38788   
...                            ...     ...        ...         ...  ...    ...   
3601            서귀포시 안덕면 일주서로 1836  서귀포시서부  33.256805  126.321630  5.0  21396   
3602        서귀포시 안덕면 신화역사로304번길 98  서귀포시서부  33.299404  126.319300  5.0  34999   
3610         서귀포시 성산읍 성산등용로 130-21  서귀포시동부  33.472110  126.933200  5.0   5956   
3626                제주시 명림로 268-71     NaN  33.461636  126.607090  5.0   3019   
3628  제주특별자치도 서귀포시 남원읍 신례리 산 12-19     NaN  33.360660  126.597206  5.0   3140   

      좋아요수  리뷰수  SNS공유수      인기점수  \
7       14   29      98  128613.0   
19       1    1       1    4528.0   
25       1    1       1    7170.0   
26       1    3       0   17242.0   
29      15   25      47   77746.0   
...    ...  ...     ...       ...   
3601     7    3      22   42828.0   
3602     7    5       9   70044.0   
3610     0    2       2   11922.0   
3626     0    1       1    6043.0   
3628     0    5       3    6305.0   

                                                     태그  \
7     #커플 #친구 #아이 #부모 #혼자 #경관/포토 #여름 #맑음 #자연경관 #포토스팟...   
19     #4.3 #문화유적지 #문화관광 #제주4.3 #역사유적 #마을산책 #마을관광 #어트랙션   
25          #부모 #커플 #혼자 #친구 #경관/포토 #오름 #사계절 #자연경관 #포토스팟   
26           #비.눈 #가을 #사계절 #겨울 #자연경관 #한라산 #언택트 #계곡 #물놀이   
29    #커플 #아이 #친구 #체험관광 #맑음 #겨울 #체험 #어린이 #어트랙션 #2022...   
...                                                 ...   
3601                              #테마공원 #맑음 #문화관광 #어트랙션   
3602   #테마공원 #맑음 #아이 #실내관광지 #어린이 #어트랙션 #안전여행스탬프 #제주신화월드   
3610                                #해변 #맑음 #자연경관 #어트랙션   
3626       #체험관광 #친구 #커플 #흐림 #사계절 #체험 #마을산책 #마을관광 #어트랙션   
3628                                #오름 #자연경관 #도보여행 #도보   

                                                     사진  \
7     https://api.cdn.visitjeju.net/photomng/imgpath...   
19    https://api.cdn.visitjeju.net/photomng/imgpath...   
25    https://api.cdn.visitjeju.net/photomng/imgpath...   
26    https://api.cdn.visitjeju.net/photomng/imgpath...   
29    https://api.cdn.visitjeju.net/photomng/imgpath...   
...                                                 ...   
3601  https://api.cdn.visitjeju.net/photomng/imgpath...   
3602  https://api.cdn.visitjeju.net/photomng/imgpath...   
3610  https://api.cdn.visitjeju.net/photomng/imgpath...   
3626  https://api.cdn.visitjeju.net/photomng/imgpath...   
3628  https://api.cdn.visitjeju.net/photomng/imgpath...   

                                                     소개  \
7                              노란 물결의 해바라기가 펼쳐진 해바라기 농장   
19                  4.3 당시 주민들이 무차별 학살을 당하고 불태워진 곤흘동 마을   
25                           한라산 관음

In [87]:
# list=[]
# for i in range(0,len(dfg)):
#     list+=kkma.nouns(dfg.iloc[i,-1])
# count=Counter(list)
# count.most_common(50)


In [88]:
tfidf_vectorizer = TfidfVectorizer()
stc=['추천 힐링 행복 추억 아름']
cos_sim=[]
for i in range(0,len(dfg)):
    stc.append(dfg.iloc[i,-1])
    
tfidf_matrix = tfidf_vectorizer.fit_transform(stc)

for i in range(0,len(dfg)):
    tfidf_matrix=tfidf_vectorizer.fit_transform(stc)
    a=i+1;b=i+2
    cos_similar=cosine_similarity(tfidf_matrix[0:1],tfidf_matrix[a:b])
    cos_sim.append(cos_similar)

[array([[0.01923738]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.00712483]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.00649679]]),
 array([[0.01321881]]),
 array([[0.00587313]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.01586127]]),
 array([[0.]]),
 array([[0.01500539]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.00749157]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.00869334]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02708539]]),
 array([[0.]]),
 array([[0.02157161]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),


In [91]:
c=np.array(cos_sim,dtype=float)
c=c.tolist()
arr=[]
for i in range(0,len(c)):
    arr.append(c[i][0][0])
dfg['코사인']=arr

In [94]:
dfg.sort_values('코사인',ascending=False)

콘텐츠ID 콘텐츠분류             제목                         지번주소  \
1027  CONT_000000000500541   관광지           제주난타         제주특별자치도 제주시 오등동 10-1   
1096  CNTS_000000000018442   관광지  누웨마루거리(구 바오젠)         제주특별자치도 제주시 연동 273-1   
311   CONT_000000000500128   관광지  당산봉(당오름,차귀오름)     제주특별자치도 제주시 한경면 고산리 산 15   
2396  CNTS_000000000018340   관광지           월평포구       제주특별자치도 서귀포시 월평동 665-4   
3306  CNTS_000000000018507   관광지        마라도관광쉼터   제주특별자치도 서귀포시 대정읍 가파리 583-9   
...                    ...   ...            ...                          ...   
1519  CONT_000000000500467   관광지        용담레포츠공원         제주특별자치도 제주시 서해안로 580   
1517  CONT_000000000500243   관광지            별도봉       제주특별자치도 제주시 선반로 (화북일동)   
1516  CONT_000000000500533   관광지      제주 삼양동 유적  제주특별자치도 제주시 선사로2길 13 (삼양일동)   
1514  CONT_000000000500689   관광지          한라수목원          제주특별자치도 제주시 수목원길 72   
3628  CNTS_000000000022752   관광지     이승이오름(이승악)              [object Object]   

                             도로명주소    지역분류         위도          경도   평점    조회수  \
1027       제주특별자치도 제주시 선돌목동길 56-26     NaN  33.445293  126.547920  5.0   9043   
1096            제주특별자치도 제주시 신광로 47     NaN  33.487740  126.490340  5.0  21381   
311       제주특별자치도 제주시 한경면 고산리 산 15   제주시서부  33.307697  126.172669  5.0   8108   
2396          제주특별자치도 서귀포시 말질로 462     NaN  33.234652  126.464789  5.0   4321   
3306      제주특별자치도 서귀포시 대정읍 마라로 139  서귀포시서부  33.114143  126.268616  4.0   1916   
...                            ...     ...        ...         ...  ...    ...   
1519          제주특별자치도 제주시 서해안로 580     NaN  33.517963  126.499610  5.0  11563   
1517        제주특별자치도 제주시 선반로 (화북일동)     제주시  33.519333  126.552997  4.0   7113   
1516   제주특별자치도 제주시 선사로2길 13 (삼양일동)     제주시  33.523994  126.586650  5.0   7697   
1514           제주특별자치도 제주시 수목원길 72     NaN  33.469604  126.491800  5.0  41597   
3628  제주특별자치도 서귀포시 남원읍 신례리 산 12-19     NaN  33.360660  126.597206  5.0   3140   

      좋아요수  리뷰수  SNS공유수     인기점수  \
1027     1    1       1  18094.0   
1096     5    7       7  42812.0   
311      4   14       3  16298.0   
2396     0    4       6   8662.0   
3306     1    2       1   3845.0   
...    ...  ...     ...      ...   
1519     0    3      25  23141.0   
1517     2    5       3  14257.0   
1516     3    3       0  15418.0   
1514     8   20      15  83318.0   
3628     0    5       3   6305.0   

                                                     태그  \
1027  #공연 #실내 #여자 #남자 #부모 #친구 #커플 #전시/행사 #비/바람/눈 #실내...   
1096                #커플 #친구 #부모 #혼자 #아이 #사계절 #어린이 #어트랙션   
311                      #오름 #걷기/등산 #가을 #자연경관 #도보여행 #도보   
2396                     #포구 #해변 #문화유적지 #맑음 #자연경관 #역사유적   
3306                                         #부모 #어트랙션    
...                                                 ...   
1519             #해변 #액티비티 #친구 #맑음 #여름 #체험 #레저/체험 #어트랙션   
1517                                #오름 #걷기/등산 #봄 #자연경관   
1516         #아이 #문화유적지 #체험관광 #전시와행사 #실내관광지 #역사유적 #어트랙션   
1514   #수목원 #휴식/힐링 #테마공원 #부모 #아이 #맑음 #여름 #자연경관 #어린이 #동백   
3628                                #오름 #자연경관 #도보여행 #도보   

                                                     사진  \
1027  https://api.cdn.visitjeju.net/photomng/imgpath...   
1096  https://api.cdn.visitjeju.net/photomng/imgpath...   
311   https://api.cdn.visitjeju.net/photomng/imgpath...   
2396  https://api.cdn.visitjeju.net/photomng/imgpath...   
3306  https://api.cdn.visitjeju.net/photomng/imgpath...   
...                                                 ...   
1519  https://api.cdn.visitjeju.net/photomng/imgpath...   
1517  https://api.cdn.visitjeju.net/photomng/imgpath...   
1516  https://api.cdn.visitjeju.net/photomng/imgpath...   
1514  https://api.cdn.visitjeju.net/photomng/imgpath...   
3628  https://api.cdn.visitjeju.net/photomng/imgpath...   

                                                     소개  \
1027     천만관객 돌파! 한국이 만들고 세계가 감동한 난타! 두드림 그 이상의 드라마 난타!   
1096                           차없는 거리로 중국관광객들이 많이 찾는 거리   
311                        한경의 푸른 바다와 고즈넉한 풍경이 있는 산책길     


In [96]:
dfs=df.groupby(df['콘텐츠분류']).get_group('숙박')

In [101]:
dfs=dfs.dropna(subset=['리뷰'])

In [106]:
dfs

콘텐츠ID 콘텐츠분류          제목                           지번주소  \
8     CNTS_200000000007048    숙박    한화리조트 제주  제주특별자치도 제주시 회천동 3-16 한화리조트 제주   
21    CNTS_000000000020153    숙박   봉쟈 게스트하우스          제주특별자치도 제주시 화북1동 1547   
42    CONT_000000000500848    숙박    라온호텔앤리조트       제주특별자치도 제주시 한림읍 협재리 2838   
63    CNTS_000000000020146    숙박       객의하우스       제주특별자치도 제주시 한림읍 협재리 1893   
75    CNTS_000000000021315    숙박        쫄깃센터     제주특별자치도 제주시 한림읍 협재리 1689-1   
...                    ...   ...         ...                            ...   
3584  CNTS_000000000020309    숙박      게으른소나기          제주 제주시 구좌읍 한동리 1287-4   
3595  CNTS_000000000020088    숙박  활엽수 게스트하우스         제주 서귀포시 대정읍 상모리 3134-2   
3608  CNTS_000000000022467    숙박       오션스퀘어             서귀포시 성산읍 온평리 648-2   
3618  CNTS_000000000022573    숙박       예이츠산장            서귀포시 남원읍 하례리 1876-1   
3621  CNTS_000000000022248    숙박        예촌민박             서귀포시 남원읍 신례리 828-8   

                                              도로명주소    지역분류         위도  \
8     제주특별자치도 제주시 명림로 575-107 (회천동, 한화리조트) 한화리조트 제주     NaN  33.448994   
21                               제주특별자치도 제주시 진동로 81     제주시  33.525860   
42                         제주특별자치도 제주시 한림읍 금능남로 127   제주시서부  33.376056   
63                        제주특별자치도 제주시 한림읍 한림로 381-3   제주시서부  33.396717   
75                          제주특별자치도 제주시 한림읍 협재1길 27   제주시서부  33.397686   
...                                             ...     ...        ...   
3584                            제주 제주시 구좌읍 계룡길 45-6   제주시동부  33.538830   
3595                          제주 서귀포시 상모대서로 20번길 44  서귀포시서부  33.225346   
3608                                 서귀포시 환해장성로 667  서귀포시동부  33.413193   
3618                              서귀포시 남원읍 516로 918  서귀포시동부  33.325466   
3621                            서귀포시 남원읍 중산간동로 7126  서귀포시동부  33.283665   

              경도   평점    조회수  좋아요수  리뷰수  SNS공유수     인기점수  \
8     126.637412  5.0  12075    13    3      12  24204.0   
21    126.568440  4.0   3986     0    2       0   7982.0   
42    126.244127  5.0   3197     0    1       0   6399.0   
63    126.243420  4.0  10281     1   10       4  20615.0   
75    126.243256  5.0   2520     0    1       5   5045.0   
...          ...  ...    ...   ...  ...     ...      ...   
3584  126.833870  5.0   5755     0    2       1  11520.0   
3595  126.261314  5.0   4471     0    5       0   8967.0   
3608  126.908860  5.0   5217     5    4       3  10469.0   
3618  126.601280  4.0   2686     0    3       0   5387.0   
3621  126.631200  5.0   1414     0    1       0   2833.0   

                                                     태그  \
8                    #콘도 #숙소 #리조트 #주차장 #공공와이파이존 #양식레스토랑   
21              #휴식 #숙소 #게스트하우스 #조식포함 #공항 #공공와이파이존 #돌담길   
42    #호텔 #숙소 #리조트 #수영장 #공공와이파이존 #주차장 #골프 #승마체험 #어린이...   
63                   #휴식 #숙소 #게스트하우스 #주차장 #공공와이파이존 #온돌방   
75                 #숙소 #게스트하우스 #문화관광 #민박 #힐링쉼터 #극장(영화관)   
...                                                 ...   
3584  #휴식 #숙소 #게스트하우스 #돌집 #조식포함 #해수욕장 #해변 #한옥 #농어촌민박...   
3595   #휴식 #숙소 #게스트하우스 #주차장 #고향민박 #온돌방 #자전거대여점 #서귀포 #조식   
3608                 #리조트 #숙소 #휴양콘도 #자연경관 #공공와이파이존 #바비큐   
3618               #펜션 #숙소 #주차장 #바비큐 #공공와이파이존 #수영장 #노래방   
3621     #숙소 #민박 #농어촌민박 #애완동물보호소 #고향민박 #자연경관 #자연학습장 #힐링   

                                                     사진  \
8     https://api.cdn.visitjeju.net/photomng/imgpath...   
21    https://api.cdn.visitjeju.net/photomng/imgpath...   
42    https://api.cdn.visitjeju.net/photomng/imgpath...   
63    https://api.cdn.visitjeju.net/photomng/imgpath...   
75    https://api.cdn.visitjeju.net/photomng/imgpath...   
...                                                 ...   
3584  https://api.cdn.visitjeju.net/photomng/imgpath...   
3595  https://api.cdn.visitjeju.net/photomng/imgpath...   
3608  https://api.cdn.visitjeju.net/photomng/imgpath...   
3618  https://api.cdn.visitjeju.net/photomng/imgpath...   
3621  https://api.cdn.visitjeju.net/photomng/imgpath...   

                                            

In [103]:
# list=[]
# for i in range(0,len(dfs)):
#     list+=kkma.nouns(dfs.iloc[i,-1])
# count=Counter(list)
# count.most_common(50)


In [113]:
tfidf_vectorizer = TfidfVectorizer()
stc=['친절 추천 편안 최고 만족 힐링']
cos_sim=[]
for i in range(0,len(dfs)):
    stc.append(dfs.iloc[i,-1])
    
tfidf_matrix = tfidf_vectorizer.fit_transform(stc)

for i in range(0,len(dfs)):
    tfidf_matrix=tfidf_vectorizer.fit_transform(stc)
    a=i+1;b=i+2
    cos_similar=cosine_similarity(tfidf_matrix[0:1],tfidf_matrix[a:b])
    cos_sim.append(cos_similar)

In [116]:
c=np.array(cos_sim,dtype=float)
c=c.tolist()
arr=[]
for i in range(0,len(c)):
    arr.append(c[i][0][0])
dfs['코사인']=arr

C:\Users\qkral_2w1w9og\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [117]:
dfs

콘텐츠ID 콘텐츠분류          제목                           지번주소  \
8     CNTS_200000000007048    숙박    한화리조트 제주  제주특별자치도 제주시 회천동 3-16 한화리조트 제주   
21    CNTS_000000000020153    숙박   봉쟈 게스트하우스          제주특별자치도 제주시 화북1동 1547   
42    CONT_000000000500848    숙박    라온호텔앤리조트       제주특별자치도 제주시 한림읍 협재리 2838   
63    CNTS_000000000020146    숙박       객의하우스       제주특별자치도 제주시 한림읍 협재리 1893   
75    CNTS_000000000021315    숙박        쫄깃센터     제주특별자치도 제주시 한림읍 협재리 1689-1   
...                    ...   ...         ...                            ...   
3584  CNTS_000000000020309    숙박      게으른소나기          제주 제주시 구좌읍 한동리 1287-4   
3595  CNTS_000000000020088    숙박  활엽수 게스트하우스         제주 서귀포시 대정읍 상모리 3134-2   
3608  CNTS_000000000022467    숙박       오션스퀘어             서귀포시 성산읍 온평리 648-2   
3618  CNTS_000000000022573    숙박       예이츠산장            서귀포시 남원읍 하례리 1876-1   
3621  CNTS_000000000022248    숙박        예촌민박             서귀포시 남원읍 신례리 828-8   

                                              도로명주소    지역분류         위도  \
8     제주특별자치도 제주시 명림로 575-107 (회천동, 한화리조트) 한화리조트 제주     NaN  33.448994   
21                               제주특별자치도 제주시 진동로 81     제주시  33.525860   
42                         제주특별자치도 제주시 한림읍 금능남로 127   제주시서부  33.376056   
63                        제주특별자치도 제주시 한림읍 한림로 381-3   제주시서부  33.396717   
75                          제주특별자치도 제주시 한림읍 협재1길 27   제주시서부  33.397686   
...                                             ...     ...        ...   
3584                            제주 제주시 구좌읍 계룡길 45-6   제주시동부  33.538830   
3595                          제주 서귀포시 상모대서로 20번길 44  서귀포시서부  33.225346   
3608                                 서귀포시 환해장성로 667  서귀포시동부  33.413193   
3618                              서귀포시 남원읍 516로 918  서귀포시동부  33.325466   
3621                            서귀포시 남원읍 중산간동로 7126  서귀포시동부  33.283665   

              경도   평점    조회수  좋아요수  리뷰수  SNS공유수     인기점수  \
8     126.637412  5.0  12075    13    3      12  24204.0   
21    126.568440  4.0   3986     0    2       0   7982.0   
42    126.244127  5.0   3197     0    1       0   6399.0   
63    126.243420  4.0  10281     1   10       4  20615.0   
75    126.243256  5.0   2520     0    1       5   5045.0   
...          ...  ...    ...   ...  ...     ...      ...   
3584  126.833870  5.0   5755     0    2       1  11520.0   
3595  126.261314  5.0   4471     0    5       0   8967.0   
3608  126.908860  5.0   5217     5    4       3  10469.0   
3618  126.601280  4.0   2686     0    3       0   5387.0   
3621  126.631200  5.0   1414     0    1       0   2833.0   

                                                     태그  \
8                    #콘도 #숙소 #리조트 #주차장 #공공와이파이존 #양식레스토랑   
21              #휴식 #숙소 #게스트하우스 #조식포함 #공항 #공공와이파이존 #돌담길   
42    #호텔 #숙소 #리조트 #수영장 #공공와이파이존 #주차장 #골프 #승마체험 #어린이...   
63                   #휴식 #숙소 #게스트하우스 #주차장 #공공와이파이존 #온돌방   
75                 #숙소 #게스트하우스 #문화관광 #민박 #힐링쉼터 #극장(영화관)   
...                                                 ...   
3584  #휴식 #숙소 #게스트하우스 #돌집 #조식포함 #해수욕장 #해변 #한옥 #농어촌민박...   
3595   #휴식 #숙소 #게스트하우스 #주차장 #고향민박 #온돌방 #자전거대여점 #서귀포 #조식   
3608                 #리조트 #숙소 #휴양콘도 #자연경관 #공공와이파이존 #바비큐   
3618               #펜션 #숙소 #주차장 #바비큐 #공공와이파이존 #수영장 #노래방   
3621     #숙소 #민박 #농어촌민박 #애완동물보호소 #고향민박 #자연경관 #자연학습장 #힐링   

                                                     사진  \
8     https://api.cdn.visitjeju.net/photomng/imgpath...   
21    https://api.cdn.visitjeju.net/photomng/imgpath...   
42    https://api.cdn.visitjeju.net/photomng/imgpath...   
63    https://api.cdn.visitjeju.net/photomng/imgpath...   
75    https://api.cdn.visitjeju.net/photomng/imgpath...   
...                                                 ...   
3584  https://api.cdn.visitjeju.net/photomng/imgpath...   
3595  https://api.cdn.visitjeju.net/photomng/imgpath...   
3608  https://api.cdn.visitjeju.net/photomng/imgpath...   
3618  https://api.cdn.visitjeju.net/photomng/imgpath...   
3621  https://api.cdn.visitjeju.net/photomng/imgpath...   

                                            

In [128]:
df1=pd.concat([dfe,dfg,dfs],axis=0)

In [126]:
df1=pd.concat([df1,dfs],axis=0)

In [129]:
df1

콘텐츠ID 콘텐츠분류          제목                        지번주소  \
5     CNTS_000000000020419   음식점      초밥군커피씨          제주특별자치도 제주시 흥운길 46   
31    CNTS_000000000022944   음식점        73st      제주특별자치도 제주시 해안동 1977-1   
37    CNTS_000000000020436   음식점       호돌이식당    제주특별자치도 제주시 한림읍 협재리 3026   
38    CNTS_000000000021195   음식점    비양도 올레카페    제주특별자치도 제주시 한림읍 협재리 2992   
45    CNTS_000000000020732   음식점     협재삼춘네횟집  제주특별자치도 제주시 한림읍 협재리 2514-9   
...                    ...   ...         ...                         ...   
3584  CNTS_000000000020309    숙박      게으른소나기       제주 제주시 구좌읍 한동리 1287-4   
3595  CNTS_000000000020088    숙박  활엽수 게스트하우스      제주 서귀포시 대정읍 상모리 3134-2   
3608  CNTS_000000000022467    숙박       오션스퀘어          서귀포시 성산읍 온평리 648-2   
3618  CNTS_000000000022573    숙박       예이츠산장         서귀포시 남원읍 하례리 1876-1   
3621  CNTS_000000000022248    숙박        예촌민박          서귀포시 남원읍 신례리 828-8   

                         도로명주소    지역분류         위도          경도   평점   조회수  \
5           제주특별자치도 제주시 흥운길 46     NaN  33.512722  126.512820  4.0  3478   
31        제주특별자치도 제주시 해안마을길 73     NaN  33.456950  126.455150  4.0  2374   
37    제주특별자치도 제주시 한림읍 비양도길 284   제주시서부  33.406414  126.230350  4.0  2180   
38     제주특별자치도 제주시 한림읍 비양도길 24   제주시서부  33.405266  126.228966  5.0  1448   
45     제주특별자치도 제주시 한림읍 한림로 318   제주시서부  33.392150  126.239560  3.0   768   
...                        ...     ...        ...         ...  ...   ...   
3584       제주 제주시 구좌읍 계룡길 45-6   제주시동부  33.538830  126.833870  5.0  5755   
3595     제주 서귀포시 상모대서로 20번길 44  서귀포시서부  33.225346  126.261314  5.0  4471   
3608            서귀포시 환해장성로 667  서귀포시동부  33.413193  126.908860  5.0  5217   
3618         서귀포시 남원읍 516로 918  서귀포시동부  33.325466  126.601280  4.0  2686   
3621       서귀포시 남원읍 중산간동로 7126  서귀포시동부  33.283665  126.631200  5.0  1414   

      좋아요수  리뷰수  SNS공유수     인기점수  \
5        3    3       2   6980.0   
31       1    1       2   4756.0   
37       0    2       0   4370.0   
38       0    1       4   2901.0   
45       0    1       0   1541.0   
...    ...  ...     ...      ...   
3584     0    2       1  11520.0   
3595     0    5       0   8967.0   
3608     5    4       3  10469.0   
3618     0    3       0   5387.0   
3621     0    1       0   2833.0   

                                                     태그  \
5                  #초밥 #용초밥 #왕초밥 #일식 #음식 #스시 #2022고메페스타   
31    #카페 #디저트 #브런치 #피자 #샐러드 #음식 #페페로니햄피자 #고르곤졸라화덕피자...   
37                   #보말죽 #한치물회 #회덮밥 #매운탕 #전복물회 #음식 #한치   
38    #카페 #커피 #생과일주스 #빙수 #음식 #아메리카노 #수제청 #수제청음료 #에이드...   
45    #횟집 #회 #회코스 #음식 #갈치조림 #제주갈치조림 #고등어조림 #갈치국 #물회 ...   
...                                                 ...   
3584  #휴식 #숙소 #게스트하우스 #돌집 #조식포함 #해수욕장 #해변 #한옥 #농어촌민박...   
3595   #휴식 #숙소 #게스트하우스 #주차장 #고향민박 #온돌방 #자전거대여점 #서귀포 #조식   
3608                 #리조트 #숙소 #휴양콘도 #자연경관 #공공와이파이존 #바비큐   
3618               #펜션 #숙소 #주차장 #바비큐 #공공와이파이존 #수영장 #노래방   
3621     #숙소 #민박 #농어촌민박 #애완동물보호소 #고향민박 #자연경관 #자연학습장 #힐링   

                                                     사진  \
5     https://api.cdn.visitjeju.net/photomng/imgpath...   
31    https://api.cdn.visitjeju.net/photomng/imgpath...   
37    https://api.cdn.visitjeju.net/photomng/imgpath...   
38    https://api.cdn.visitjeju.net/photomng/imgpath...   
45    https://api.cdn.visitjeju.net/photomng/imgpath...   
...                                                 ...   
3584  https://api.cdn.visitjeju.net/photomng/imgpath...   
3595  https://api.cdn.visitjeju.net/photomng/imgpath...   
3608  https://api.cdn.visitjeju.net/photomng/imgpath...   
3618  https://api.cdn.visitjeju.net/photomng/imgpath...   
3621  https://api.cdn.visitjeju.net/photomng/imgpath...   

                                       소개  \
5                  크기가 어마어마한 직접 만들어먹는 용초밥   
31            엔티크하고 분위기있는 인테리어를 갖춘 브런치 카페   
37                       인기메뉴는 호돌이덮밥과 보말죽   
38    비양도항 앞에 위치한 카페, 아메리카노와 생과일쥬스를 주로 판매   
45              협재 바닷가쪽에 위치한 협재 삼춘네횟집입니다.   
...                                   ...   
3584       약 100년 전통의 제주 돌집을 

In [132]:
df2=df[df['리뷰'].isnull()]

In [133]:
df2=pd.concat([df1,df2])

In [134]:
df2

콘텐츠ID 콘텐츠분류                   제목  \
5     CNTS_000000000020419   음식점               초밥군커피씨   
31    CNTS_000000000022944   음식점                 73st   
37    CNTS_000000000020436   음식점                호돌이식당   
38    CNTS_000000000021195   음식점             비양도 올레카페   
45    CNTS_000000000020732   음식점              협재삼춘네횟집   
...                    ...   ...                  ...   
3617  CNTS_000000000022182   음식점  몽키비치클럽 Monkey Beach   
3620  CNTS_000000000022252    숙박               힐링캠프펜션   
3622  CNTS_000000000022237   음식점                 유나카페   
3623  CNTS_200000000008003   관광지               동백포레스트   
3624  CNTS_200000000012075   관광지           헌마공신김만일기념관   

                            지번주소                     도로명주소    지역분류         위도  \
5             제주특별자치도 제주시 흥운길 46        제주특별자치도 제주시 흥운길 46     NaN  33.512722   
31        제주특별자치도 제주시 해안동 1977-1      제주특별자치도 제주시 해안마을길 73     NaN  33.456950   
37      제주특별자치도 제주시 한림읍 협재리 3026  제주특별자치도 제주시 한림읍 비양도길 284   제주시서부  33.406414   
38      제주특별자치도 제주시 한림읍 협재리 2992   제주특별자치도 제주시 한림읍 비양도길 24   제주시서부  33.405266   
45    제주특별자치도 제주시 한림읍 협재리 2514-9   제주특별자치도 제주시 한림읍 한림로 318   제주시서부  33.392150   
...                          ...                       ...     ...        ...   
3617             서귀포시 색달동 2822-2       서귀포시 중문관광로72번길 29-9    서귀포시  33.249680   
3620         서귀포시 남원읍 위미리 3392-1         서귀포시 남원읍 위미항구로 96  서귀포시동부  33.282875   
3622           서귀포시 남원읍 신례리 57-1          서귀포시 남원읍 공천포로 81  서귀포시동부  33.266018   
3623           서귀포시 남원읍 신례리 1767         서귀포시 남원읍 신례리 1767  서귀포시동부  33.299995   
3624            서귀포시 남원읍 서성로 919          서귀포시 남원읍 서성로 919  서귀포시동부        NaN   

              경도   평점   조회수  좋아요수  리뷰수  SNS공유수     인기점수  \
5     126.512820  4.0  3478     3    3       2   6980.0   
31    126.455150  4.0  2374     1    1       2   4756.0   
37    126.230350  4.0  2180     0    2       0   4370.0   
38    126.228966  5.0  1448     0    1       4   2901.0   
45    126.239560  3.0   768     0    1       0   1541.0   
...          ...  ...   ...   ...  ...     ...      ...   
3617  126.411360  NaN  3509     2    0       2   7024.0   
3620  126.655720  NaN   762     0    0       2   1524.0   
3622  126.641820  NaN   908     0    0       1   1816.0   
3623  126.629794  0.0  7682     5    0       6  15379.0   
3624         NaN  0.0   142     1    0       0    287.0   

                                                     태그  \
5                  #초밥 #용초밥 #왕초밥 #일식 #음식 #스시 #2022고메페스타   
31    #카페 #디저트 #브런치 #피자 #샐러드 #음식 #페페로니햄피자 #고르곤졸라화덕피자...   
37                   #보말죽 #한치물회 #회덮밥 #매운탕 #전복물회 #음식 #한치   
38    #카페 #커피 #생과일주스 #빙수 #음식 #아메리카노 #수제청 #수제청음료 #에이드...   
45    #횟집 #회 #회코스 #음식 #갈치조림 #제주갈치조림 #고등어조림 #갈치국 #물회 ...   
...                                                 ...   
3617                                               #음식    
3620  #숙소 #휴양펜션 #펜션 #캠핑 #독채 #온돌방 #바비큐 #단체여행객 #공공와이파이...   
3622  #카페 #커피 #생과일주스 #감귝샐러드 #음식 #보말칼국수 #허니브레드 #자몽에이드...   
3623             #커플 #친구 #맑음 #경관/포토 #겨울 #자연경관 #동백 #포토스팟   
3624  #커플 #부모 #혼자 #친구 #아이 #맑음 #흐림 #비.눈 #경관/포토 #휴식/힐링...   

                                                     사진  \
5     https://api.cdn.visitjeju.net/photomng/imgpath...   
31    https://api.cdn.visitjeju.net/photomng/imgpath...   
37    https://api.cdn.visitjeju.net/photomng/imgpath...   
38    https://api.cdn.visitjeju.net/photomng/imgpath...   
45    https://api.cdn.visitjeju.net/photomng/imgpath...   
...                                                 ...   
3617  https://api.cdn.visitjeju.net/photomng/imgpath...   
3620  https://api.cdn.visitjeju.net/photomng/imgpath...   
3622  https://api.cdn.visitjeju.net/photomng/imgpath...   
3623  https://api.cdn.visitjeju.net/photomng/imgpath...   
3624  https://api.cdn.visitjeju.net/photomng/imgpath...   

                                                     소개  \
5                                크기가 어마어마한 직접 만들어먹는 용초밥   
31                          엔티크하고 분위기있는 인테리어를 갖춘 브런치 카페   
37                                     인기메뉴는 호돌이덮밥과 보말죽   


In [135]:
df2.to_excel('jeju place2.xlsx')